version: '3.7'

name: agilne-2022-23-draganovik
services:

  zipkin-server:
    image: openzipkin/zipkin:3.1
    ports:
      - "9411:9411"
    networks:
      - currency-network

  api-gateway:
    image: draganovik/api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - user-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  naming-server:
    image: draganovik/naming-server:latest
    build:
      context: ./naming-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - currency-network

  user-service:
    image: draganovik/user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8770:8770"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  currency-exchange:
    image: draganovik/currency-exchange:latest
    build:
      context: ./currency-exchange
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  currency-conversion:
    image: draganovik/currency-conversion:latest
    build:
      context: ./currency-conversion
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - bank-account
      - currency-exchange
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  bank-account:
    image: draganovik/bank-account:latest
    build:
      context: ./bank-account
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - user-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  crypto-wallet:
    image: draganovik/crypto-wallet:latest
    build:
      context: ./crypto-wallet
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - user-service
      - bank-account
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  crypto-exchange:
    image: draganovik/crypto-exchange:latest
    build:
      context: ./crypto-exchange
      dockerfile: Dockerfile
    ports:
      - "8400:8400"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  crypto-conversion:
    image: draganovik/crypto-conversion:latest
    build:
      context: ./crypto-conversion
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - crypto-wallet
      - crypto-exchange
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  trade-service:
    image: draganovik/trade-service:latest
    build:
      context: ./trade-service
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - crypto-wallet
      - bank-account
      - currency-exchange
      - currency-conversion
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  transfer-service:
    image: draganovik/transfer-service:latest
    build:
      context: ./transfer-service
      dockerfile: Dockerfile
    ports:
      - "8700:8700"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - bank-account
      - crypto-wallet
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

networks:
  currency-network: